[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
hound = "3.5.1"
# mini_sdl = "0.2.7"
mini_sdl = { path = "/Users/leo/Documents/Code/rust/_crates/mini_sdl" }
soundchip = { path = "../" }
